"""create users table

Revision ID: 70e54af7b0d0
Revises: b3db01fd7256
Create Date: 2026-08-13 14:40:19.838298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e54af7b0d0'
down_revision: Union[str, Sequence[str], None] = 'b3db01fd7256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_division_id'), 'users', ['division_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_no', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending_checker', 'pending_approver', 'approved', 'rejected', 'closed', 'cancelled', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='ticket_priority'), nullable=False),
    sa.Column('maker_id', sa.UUID(), nullable=False),
    sa.Column('checker_id', sa.UUID(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checker_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approver_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checker_cycle_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approval_cycle_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cycle_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=False),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            status NOT IN ('closed', 'rejected', 'cancelled')\n            OR closed_at IS NOT NULL\n            ", name='chk_terminal_status_has_closure'),
    sa.CheckConstraint('checker_id IS NULL OR checker_id <> maker_id', name='chk_maker_not_checker'),
    sa.CheckConstraint('closed_at IS NULL OR closed_at >= created_at', name='chk_closure_after_creation'),
    sa.CheckConstraint('total_cycle_hours IS NULL OR total_cycle_hours >= 0', name='chk_cycle_non_negative'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_approver_id'), 'tickets', ['approver_id'], unique=False)
    op.create_index(op.f('ix_tickets_checker_id'), 'tickets', ['checker_id'], unique=False)
    op.create_index(op.f('ix_tickets_division_id'), 'tickets', ['division_id'], unique=False)
    op.create_index(op.f('ix_tickets_is_escalated'), 'tickets', ['is_escalated'], unique=False)
    op.create_index(op.f('ix_tickets_maker_id'), 'tickets', ['maker_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_reference_no'), 'tickets', ['reference_no'], unique=True)
    op.create_index(op.f('ix_tickets_sla_breached'), 'tickets', ['sla_breached'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_type_id'), 'tickets', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_type_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sla_breached'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_reference_no'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_maker_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_is_escalated'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_division_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_checker_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_approver_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_division_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
