"""add workflow escalation and refresh tokens

Revision ID: bea85752f9e8
Revises: 70e54af7b0d0
Create Date: 2026-08-13 14:52:25.896703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea85752f9e8'
down_revision: Union[str, Sequence[str], None] = '70e54af7b0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', name='escalation_level'), nullable=False),
    sa.Column('reason', sa.Enum('SLA_BREACH', 'AWAITING_APPROVAL', 'INCOMPLETE_DOCS', 'POLICY_EXCEPTION', 'DATA_MISMATCH', 'EXTERNAL_DEPENDENCY', name='escalation_reason'), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'withdrawn', name='escalation_status'), nullable=False),
    sa.Column('raised_by_id', sa.UUID(), nullable=False),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_raised_by_id'), 'escalations', ['raised_by_id'], unique=False)
    op.create_index(op.f('ix_escalations_resolved_by_id'), 'escalations', ['resolved_by_id'], unique=False)
    op.create_index(op.f('ix_escalations_ticket_id'), 'escalations', ['ticket_id'], unique=False)
    op.create_table('ticket_stage_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('created', 'checker', 'approver', 'closure', name='stage_name'), nullable=False),
    sa.Column('action', sa.Enum('submitted', 'approved', 'rejected', 'returned', 'closed', name='stage_action'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_stage_events_actor_id'), 'ticket_stage_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ticket_stage_events_occurred_at'), 'ticket_stage_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_ticket_stage_events_ticket_id'), 'ticket_stage_events', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_stage_events_ticket_id'), table_name='ticket_stage_events')
    op.drop_index(op.f('ix_ticket_stage_events_occurred_at'), table_name='ticket_stage_events')
    op.drop_index(op.f('ix_ticket_stage_events_actor_id'), table_name='ticket_stage_events')
    op.drop_table('ticket_stage_events')
    op.drop_index(op.f('ix_escalations_ticket_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_resolved_by_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_raised_by_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
